name: ruangkeluarga
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# flutter.versionName=0.0.31-alpha
# flutter.versionCode=220000310A
# versionCode: minSDK + major 00 + minor 62+ patch 01 +testing 0 + Alpha / Beta / Release
version: 0.0.38+220000368A

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  admin: ^0.0.4
  app_usage: ^2.0.0
  audioplayers: ^0.19.1

  badges: ^2.0.1

  camera: ^0.9.2+2
  cupertino_icons: ^1.0.2
  charts_flutter: ^0.11.0

  device_apps: ^2.1.1

  http: ^0.13.3

  image_cropper: ^1.4.1
  image_picker: ^0.8.4
  intl: ^0.17.0

  firebase_core: ^1.2.1
  firebase_analytics: ^8.2.0
  firebase_messaging: ^10.0.1
  fluttertoast: ^8.0.7
  flutter_app_lock: ^2.0.0
  flutter_background_service: ^0.1.5
  flutter_contacts: ^1.1.0+3
  flutter_local_notifications: ^8.1.1
  flutter_notification_channel: ^2.0.0
#  flutter_datetime_picker:
#    git:
#      url: https://github.com/AlexHartford/flutter_datetime_picker.git
#      ref: master
  flutter_datetime_picker: ^1.5.1
  flutter_geocoder:
    git:
      url: https://github.com/JCKodel/flutter_geocoder.git
      ref: "7059f6f"

  get:
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.4

  location: ^4.3.0
#  location_permissions: ^4.0.0

  package_info_plus: ^1.0.6
  path_provider: ^2.0.2
  permission_handler: ^8.1.0
  provider: ^5.0.0

  qr_flutter: ^4.0.0

  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_charts: ^19.2.56

  #  usage_stats: ^0.1.0

  video_player: ^2.1.9

  webview_flutter: ^2.0.13

  youtube_player_flutter: ^8.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator:
#flutter pub run dependency_validator
  flutter_launcher_icons:
  flutter_native_splash:
  change_app_package_name: ^1.0.0
  #flutter pub run change_app_package_name:main com.keluargahkbp

flutter_icons:
  android: 'launcher_icon'
  ios: true
  # image_path: "assets/images/hkbp/logo-keluargahkbp.png"
  image_path_ios: "assets/images/hkbp/ic_launcher.png"
  image_path_android: "assets/images/hkbp/ic_launcher.png"
  adaptive_icon_background: 'assets/images/hkbp/ic_launcher_adaptive_back.png'
  adaptive_icon_foreground: 'assets/images/hkbp/ic_launcher_adaptive_fore.png'
# flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: '#333333'
  image: 'assets/images/hkbp/logo-keluargahkbp.png'
  android: true
  ios: true
# flutter pub run flutter_native_splash:create

## generate SHA fingerprint android:
## keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/hkbp/
