name: ruangkeluarga
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remgoogle_mobile_ads: ^1.0.1ove this line if you wish to publish to pub.dev

# flutter.versionName=0.0.31-alpha
# flutter.versionCode=220000310A
# versionCode: minSDK + major 00 + minor 62+ patch 01 +testing 0 + Alpha / Beta / Release
version: 0.0.579+220000398B

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  admin: ^0.0.4
  app_usage: ^2.0.0
  audioplayers: ^0.20.1

  badges: ^2.0.2

  camera: ^0.9.4+21
  cupertino_icons: ^1.0.4
  charts_flutter: ^0.12.0
  device_apps: ^2.1.1
  device_info: ^2.0.3
  geolocator: ^8.0.3
  minimize_app: ^0.1.1
  usage_stats: ^1.1.1

  http: ^0.13.4

  image_cropper: ^1.4.1
  image_picker: ^0.8.5
  intl: ^0.17.0

  firebase_analytics: ^9.0.5
  firebase_messaging: ^11.2.5
  firebase_core: ^1.11.0
  firebase_database: ^9.0.5
  fluttertoast: ^8.0.8
  flutter_app_lock: ^2.0.0
#  flutter_background_service: ^0.1.5
  flutter_contacts: ^1.1.3
  flutter_local_notifications: ^9.2.0
  flutter_notification_channel: ^2.0.0
#  flutter_datetime_picker:
#    git:
#      url: https://github.com/AlexHartford/flutter_datetime_picker.git
#      ref: master
  flutter_datetime_picker: ^1.5.1
  google_maps_flutter: ^2.1.1
  google_sign_in: ^5.2.3
  location: ^4.3.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  provider: ^6.0.2
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_charts: ^19.4.42
  video_player: ^2.2.11
  webview_flutter: ^3.0.0
  youtube_player_flutter: ^8.0.0
  firebase_crashlytics: ^2.4.5
  flutter_screen_lock: ^5.0.3
  sqflite: ^2.0.2
  flutter_geocoder:
    git:
      url: https://github.com/JCKodel/flutter_geocoder.git
      ref: "7059f6f"
  get:
  app_settings: ^4.1.1
  device_info_plus: ^3.2.2
  flutter_native_config: ^1.0.0
  native_pdf_view: ^5.0.0
  # pdfx: ^2.0.1+2
  internet_file: ^1.0.0+2
  url_launcher: ^6.1.0
  flutter_html: ^3.0.0-alpha.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator:
#flutter pub run dependency_validator
  flutter_launcher_icons:
  flutter_native_splash:
  change_app_package_name: ^1.0.0
  #flutter pub run change_app_package_name:main com.byasia.ruangortu

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "assets/images/asia/asia.ruangortu.png"
  # flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: '#333333'
  image: 'assets/images/asia/asia.ruangortu.png'
  android: true
  ios: true
# flutter pub run flutter_native_splash:create


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/asia/
    - assets/images/icon/